### ISSUE TITLE
GPSLogger To-Do Punchlist

### ISSUE THREAD

**Issue by knight-of-ni** [knight-of-ni/gpspi#1]
Here are a current list of features planned to be implemented or improved:

- [ ] Package the project with distutils a.k.a. setup.py
- [ ] Timezone is currently hardcoded to central time. Make this changable and/or automatic
- [ ] Make the DS18B20 temperature probe optional
- [ ] Evaluate dynamic means to determine how often to take a photo, rather than every X feet. For instance, automatically vary the minimum distance required to be traveled, based on one's speed.
- [ ] The trigger to take a photo now has not been tested
- [ ] Consider more triggers (buttons) to allow additional functionality such as clean shutdown, stop/start logging, wifi on/off, etc.
- [ ] Evaluate alternative auto-hotspot tools
